---
title: "Map"
author: "Naaman Omar"
date: "09/08/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(rgdal)
library(tidyverse)
```

```{r}
# shp file can be downloaded from the canada 2021 census https://www12.statcan.gc.ca/census-recensement/alternative_alternatif.cfm?l=eng&dispext=zip&teng=lcd_000b21a_e.zip&k=%20%20%20136594&loc=//www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/boundary-limites/files-fichiers/lcd_000b21a_e.zip
canada_cd <- read_sf(dsn = file.path("..", "lcd_000b21a_e//lcd_000b21a_e.shp"))
crs_string2 = "+proj=lcc +lat_1=40 +lat_2=50 +lon_0=-75 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"
```

```{r}
crs_string2 = "+proj=lcc +lat_1=40 +lat_2=50 +lon_0=-75 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"
zoom_to <- c(-64.3683, 45.8979) # Sackville, New Brunswick; could try c(-63.5752, 44.6488)  # Halifax
zoom_level <- 7
C <- 40075016.686   # ~ circumference of Earth in meters
x_span <- C / 2^zoom_level
y_span <- C / 2^(zoom_level)
zoom_to_xy <- st_transform(st_sfc(st_point(zoom_to), crs = 4326),
                           crs = crs_string2)
disp_window <- st_sfc(
    st_point(st_coordinates(zoom_to_xy - c(x_span / 2, y_span / 2))),
    st_point(st_coordinates(zoom_to_xy + c(x_span / 2, y_span / 2))),
    crs = crs_string2
)

label_data <- data.frame(
  x = c(-64.929960, -64.524428, -64.509637),  # Longitude , °, 
  y = c(46.848534, 46.281516, 46.239706),   # Latitude
  label = c("Kouchibouguac Bay", "Shediac Bay", "Parlee Beach Provincial Park") 
) %>%
  st_as_sf(coords = c("x", "y"), crs = 4326) %>%  # Set the CRS as WGS84 (EPSG:4326)
  st_transform(crs = crs_string2)  # Transform to the map's CRS


```

```{r}
disp_window_4326 <- st_transform(disp_window, crs = 4326)
(Map <- canada_cd %>%
  filter(PRUID %in% c(11,12,13)) %>% 
ggplot() +
  geom_rect(xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "skyblue") + # blue background
  geom_sf(fill = "white", color = "black", size = 0.01) + # please keep this will hide the effect of alpha on the next line
  geom_sf(aes(fill = PRUID), color = "black", size = 0.01, alpha = 0.2) + # provinces and their colors
  geom_sf(data = label_data, color = 'black', fill = "red", size = 2, shape = 21) +# points on map
  coord_sf(xlim = st_coordinates(disp_window)[,'X'],
           ylim = st_coordinates(disp_window)[,'Y'],
           crs = crs_string2, datum = crs_string2,
           expand = FALSE) +
  coord_sf(
    xlim = st_coordinates(disp_window_4326)[,'X'],
    ylim = st_coordinates(disp_window_4326)[,'Y'],
    crs = 4326, 
    datum = 4326
  ) +
annotate(
    "label", 
    x = -64.929960 + 0.2, 
    y = 46.848534, 
    label = "Kouchibouguac Bay", 
    color = "black", 
    size = 4,
    fontface = "bold",
    hjust = 0
  ) +
  annotate(
    "segment",
    x = -64.929960, 
    y = 46.848534,
    xend = -64.929960 + 0.2,
    yend = 46.848534,
    arrow = arrow(length = unit(0.2, "cm")),
    color = "black"
  ) +
  
  annotate(
    "label", 
    x = -64.524428 + 0.2, 
    y = 46.281516 + 0.1, 
    label = "Shediac Bay", 
    color = "black", 
    size = 4,
    fontface = "bold",
    hjust = 0
  ) +
  annotate(
    "segment",
    x = -64.524428, 
    y = 46.281516,
    xend = -64.524428 + 0.2,
    yend = 46.281516 + 0.1,
    arrow = arrow(length = unit(0.2, "cm")),
    color = "black"
  ) +
  
  annotate(
    "label", 
    x = -64.509637 + 0.2, 
    y = 46.239706 - 0.1, 
    label = "Parlee Beach Provincial Park", 
    color = "black", 
    size = 4,
    fontface = "bold",
    hjust = 0
  ) +
  annotate(
    "segment",
    x = -64.509637, 
    y = 46.239706,
    xend = -64.509637 + 0.2,
    yend = 46.239706 - 0.1,
    arrow = arrow(length = unit(0.2, "cm")),
    color = "black"
  ) +
  annotate(
    "label", 
    x = -66.5, 
    y = 46, 
    label = "New Brunswick", 
    color = "white", 
    size = 5,
    fill = "black",
    alpha = 0.6,
    fontface = "bold",
    hjust = 0
  ) +
  annotate(
    "label", 
    x = -64, 
    y = 45, 
    label = "Nova Scotia", 
    color = "white", 
    size = 5,
    fill = "black",
    alpha = 0.6,
    fontface = "bold",
    hjust = 0
  ) +
  scale_fill_manual(values = c("yellow", "green", "red")) +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    panel.grid.major = element_line(color = "white"),
    legend.position = "none",
    legend.key = element_rect(color = "gray40", size = 0.1)
  ) +
  labs(x = "Longitude (°)", y = "Latitude (°)"))
```

```{r}
ggsave(plot = Map, filename = file.path("..", "Figures", "Map.png"), width = 7, height = 5)
ggsave(plot = Map, filename = file.path("..", "Figures", "Fig1.tiff"), width = 7, height = 5)
```

